import { NextResponse } from "next/server";
import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import { pool } from "@/lib/db";
import { log, errorInfo } from "@/lib/log";

/**
 * Alert feed for the signed-in user.
 *
 *   GET  /api/alerts        → list open alerts (not dismissed)
 *   POST /api/alerts        → { id: string, action: 'seen' | 'dismiss' }
 *
 * Alerts are generated by the nightly cron (lib/alerts.ts scanners) from
 * free data sources — price moves, Form 4 insider transactions,
 * concentration thresholds. No AI is involved in generation.
 */

export async function GET() {
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session) {
    return NextResponse.json({ items: [] }, { status: 401 });
  }

  try {
    const { rows } = await pool.query(
      `SELECT id, kind, ticker, severity, title, body, metadata,
              "seenAt", "createdAt"
       FROM "alert_event"
       WHERE "userId" = $1
         AND "dismissedAt" IS NULL
       ORDER BY "createdAt" DESC
       LIMIT 50`,
      [session.user.id]
    );
    const items = rows.map((r: Record<string, unknown>) => ({
      id: r.id as string,
      kind: r.kind as string,
      ticker: (r.ticker as string | null) ?? null,
      severity: r.severity as string,
      title: r.title as string,
      body: (r.body as string | null) ?? null,
      metadata: r.metadata ?? {},
      seen: r.seenAt != null,
      createdAt:
        r.createdAt instanceof Date
          ? r.createdAt.toISOString()
          : String(r.createdAt),
    }));
    return NextResponse.json({ items });
  } catch (err) {
    log.warn("alerts.list", "failed", { ...errorInfo(err) });
    return NextResponse.json({ items: [] });
  }
}

export async function POST(req: Request) {
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: { id?: string; action?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const id = body.id?.trim();
  const action = body.action;
  if (!id || (action !== "seen" && action !== "dismiss")) {
    return NextResponse.json(
      { error: "Provide id + action ('seen' | 'dismiss')" },
      { status: 400 }
    );
  }

  try {
    const column = action === "dismiss" ? `"dismissedAt"` : `"seenAt"`;
    // userId filter enforces ownership — can't mark someone else's alert.
    await pool.query(
      `UPDATE "alert_event"
       SET ${column} = COALESCE(${column}, NOW())
       WHERE id = $1 AND "userId" = $2`,
      [id, session.user.id]
    );
    return NextResponse.json({ ok: true });
  } catch (err) {
    log.warn("alerts.update", "failed", { id, action, ...errorInfo(err) });
    return NextResponse.json({ error: "Could not update" }, { status: 500 });
  }
}
