import type { Metadata } from "next";
import Link from "next/link";
import MarketingNav from "@/components/marketing/nav";
import MarketingFooter from "@/components/marketing/footer";

export const metadata: Metadata = {
  title: "Disclosures — ClearPath Invest",
  description:
    "Disclosures regarding the nature of the Service, data sources, AI model usage, and limitations.",
};

export default function DisclosuresPage() {
  return (
    <>
      <MarketingNav />
      <main className="mx-auto max-w-3xl px-6 py-16 lg:py-24">
        <div className="mb-8 rounded-md border border-[var(--hold)]/40 bg-[var(--hold)]/5 p-4 text-sm">
          <p className="font-medium">Draft for attorney review.</p>
          <p className="mt-1 text-muted-foreground">
            These disclosures have not been finalized by licensed counsel and
            should be reviewed before paid launch.
          </p>
        </div>

        <h1 className="font-[family-name:var(--font-display)] text-4xl font-medium tracking-tight">
          Disclosures
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Effective date: 2026-04-15.
        </p>

        <div className="prose prose-sm mt-10 max-w-none leading-relaxed dark:prose-invert [&_h2]:mt-10 [&_h2]:font-[family-name:var(--font-display)] [&_h2]:text-2xl [&_h2]:font-medium [&_h3]:mt-6 [&_h3]:text-base [&_h3]:font-semibold [&_p]:mt-3 [&_ul]:mt-2 [&_ul]:list-disc [&_ul]:pl-6 [&_li]:mt-1">
          <h2>What ClearPath is — and what it isn&rsquo;t</h2>
          <p>
            ClearPath Invest is a <strong>research tool</strong> that uses
            public data and third-party AI models to produce informational
            analyses about publicly traded securities. ClearPath is{" "}
            <strong>not</strong> a registered investment advisor, broker-dealer,
            financial planner, fiduciary, CPA, or attorney. Nothing on the
            Service is investment, tax, legal, or accounting advice.
          </p>
          <p>
            Recommendations produced by the Service (BUY / HOLD / SELL /
            INSUFFICIENT_DATA) are informational labels generated by automated
            software comparing outputs of three independent large language
            models against verified primary data. They are not instructions,
            solicitations, or offers to transact in any security.
          </p>

          <h2>AI model disclosure</h2>
          <p>
            Research analyses are produced using the following third-party AI
            providers:
          </p>
          <ul>
            <li>
              <strong>Anthropic Claude (Sonnet 4.6, Haiku 4.5)</strong> — value
              lens and supervisor rotation.
            </li>
            <li>
              <strong>OpenAI GPT (5.2)</strong> — growth lens and supervisor
              rotation.
            </li>
            <li>
              <strong>Google Gemini (3 Pro)</strong> — macro-contrarian lens
              and supervisor rotation.
            </li>
          </ul>
          <p>
            Each model receives the same verified public data. A rotating
            supervisor model independently reviews all three outputs and flags
            any numeric claim not present in the source data. Model outputs
            may still be incomplete, biased, or incorrect.
          </p>
          <p>
            We do not fine-tune these models on your personal data. Providers
            may retain prompts for abuse monitoring per their own policies but
            do not train on your data without your consent (per their
            published policies at time of integration).
          </p>

          <h2>Data sources</h2>
          <p>
            The Service aggregates data from the following sources. Each source
            may be delayed, incomplete, or contain errors. We make no warranty
            regarding timeliness or accuracy.
          </p>
          <ul>
            <li>
              <strong>SEC EDGAR</strong> — company filings (10-K, 10-Q, 8-K,
              DEF 14A). Free public API.
            </li>
            <li>
              <strong>FRED (Federal Reserve Economic Data)</strong> — macro
              indicators including Treasury yields, Fed funds rate, CPI,
              unemployment, VIX.
            </li>
            <li>
              <strong>Yahoo Finance</strong> — quote data, fundamentals, analyst
              consensus. Yahoo Finance is a third-party service and not
              affiliated with ClearPath.
            </li>
            <li>
              <strong>SnapTrade</strong> — brokerage account linking and
              portfolio data (read-only). Subject to SnapTrade&apos;s own
              terms and limitations.
            </li>
          </ul>

          <h2>Track record disclosure</h2>
          <p>
            We store every recommendation and evaluate outcomes at 7, 30, 90,
            and 365 days. Historical track-record statistics are purely
            informational. <strong>Past performance does not guarantee
            future results.</strong> Evaluated outcomes:
          </p>
          <ul>
            <li>
              Use our stored price at the time of the recommendation and a
              cached current price from Yahoo Finance — these may differ from
              the price you would actually pay.
            </li>
            <li>
              Do not account for taxes, transaction costs, slippage, dividends,
              or corporate actions.
            </li>
            <li>
              Use a simple percent-move threshold to categorize win / loss /
              flat. They are not risk-adjusted returns and should not be
              compared to benchmark indices.
            </li>
            <li>
              May reflect selection effects (users research tickers they were
              already considering, not a random sample).
            </li>
          </ul>

          <h2>Conflicts of interest</h2>
          <p>
            ClearPath does not accept payments from issuers of securities,
            brokerages, or asset managers in exchange for favorable coverage.
            We do not earn commissions, referral fees, or payment for order
            flow. Our revenue comes solely from user subscriptions and, if
            applicable, partnerships clearly disclosed on this page.
          </p>
          <p>
            Employees and contractors of ClearPath may own positions in
            securities discussed by the Service. No employee may trade on
            the basis of non-public information generated by the Service.
          </p>

          <h2>No solicitation</h2>
          <p>
            This Service is not an offer to sell or a solicitation of an offer
            to buy any security in any jurisdiction where such an offer or
            solicitation would be illegal. Users outside the United States
            should consult local law before acting on any information.
          </p>

          <h2>Security-specific risks</h2>
          <p>
            All securities investments carry risk of loss, including the loss
            of principal. Past performance is not indicative of future
            results. Market prices, valuations, and other inputs are volatile.
            Specific risks include but are not limited to: market risk,
            liquidity risk, credit risk, regulatory risk, concentration risk,
            currency risk, and counterparty risk.
          </p>

          <h2>Contact</h2>
          <p>
            <a href="mailto:disclosures@clearpath-invest.com" className="underline">
              disclosures@clearpath-invest.com
            </a>
            . See also our{" "}
            <Link href="/terms" className="underline">
              Terms
            </Link>{" "}
            and{" "}
            <Link href="/privacy" className="underline">
              Privacy Policy
            </Link>
            .
          </p>
        </div>
      </main>
      <MarketingFooter />
    </>
  );
}
