import type { Metadata } from "next";
import Link from "next/link";
import MarketingNav from "@/components/marketing/nav";
import MarketingFooter from "@/components/marketing/footer";

export const metadata: Metadata = {
  title: "Terms of Service — ClearPath Invest",
  description:
    "The terms governing your use of ClearPath Invest, including important disclaimers about the informational nature of our service.",
};

export default function TermsPage() {
  return (
    <>
      <MarketingNav />
      <main className="mx-auto max-w-3xl px-6 py-16 lg:py-24">
        <div className="mb-8 rounded-md border border-[var(--hold)]/40 bg-[var(--hold)]/5 p-4 text-sm">
          <p className="font-medium">Draft for attorney review.</p>
          <p className="mt-1 text-muted-foreground">
            This document reflects our intended legal posture but has not been
            finalized by licensed counsel. It should be reviewed by a qualified
            attorney before ClearPath Invest accepts paying customers.
          </p>
        </div>

        <h1 className="font-[family-name:var(--font-display)] text-4xl font-medium tracking-tight">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Effective date: 2026-04-15. Last updated: 2026-04-15.
        </p>

        <div className="prose prose-sm mt-10 max-w-none leading-relaxed dark:prose-invert [&_h2]:mt-10 [&_h2]:font-[family-name:var(--font-display)] [&_h2]:text-2xl [&_h2]:font-medium [&_h3]:mt-6 [&_h3]:text-base [&_h3]:font-semibold [&_p]:mt-3 [&_ul]:mt-2 [&_ul]:list-disc [&_ul]:pl-6 [&_li]:mt-1">
          <h2>1. Agreement to these terms</h2>
          <p>
            These Terms of Service (&ldquo;<strong>Terms</strong>&rdquo;) are a
            binding agreement between you and ClearPath Invest (&ldquo;
            <strong>ClearPath</strong>,&rdquo; &ldquo;<strong>we</strong>,&rdquo;
            &ldquo;<strong>us</strong>,&rdquo; or &ldquo;<strong>our</strong>
            &rdquo;) governing your access to and use of the ClearPath Invest
            website, web application, and related services (together, the
            &ldquo;<strong>Service</strong>&rdquo;). By creating an account,
            accessing, or using the Service, you agree to these Terms and to
            our{" "}
            <Link href="/privacy" className="underline">
              Privacy Policy
            </Link>{" "}
            and{" "}
            <Link href="/disclosures" className="underline">
              Disclosures
            </Link>
            . If you do not agree, do not use the Service.
          </p>

          <h2>2. Eligibility</h2>
          <p>
            You must be at least 18 years old and legally able to enter into a
            binding contract. By using the Service, you represent that these
            conditions are met and that you are not barred from using the
            Service under the laws of the United States or the jurisdiction in
            which you reside.
          </p>

          <h2>3. The Service is informational — not investment advice</h2>
          <p>
            <strong>
              The Service is an informational research tool. It does not
              provide investment, tax, legal, accounting, or fiduciary advice.
            </strong>{" "}
            ClearPath is not a registered investment advisor, broker-dealer,
            financial planner, or fiduciary, and no portion of the Service
            constitutes a solicitation, offer, or recommendation to buy, sell,
            or hold any security, option, futures contract, cryptocurrency, or
            other financial instrument.
          </p>
          <p>
            Outputs generated by the Service — including recommendations,
            confidence ratings, consensus labels, track-record data, portfolio
            analyses, model outputs, and summaries — are produced by automated
            software and large language models. These outputs may be
            inaccurate, incomplete, biased, outdated, or wrong. You are solely
            responsible for your investment decisions and for verifying any
            information before acting on it.
          </p>
          <p>
            Past performance does not guarantee future results. Historical
            outcome tracking on the Service is informational only and is not a
            predictor of future performance. Market prices, interest rates,
            volatility, and other conditions change continuously; the Service
            may use data that is delayed, cached, or inaccurate.
          </p>

          <h2>4. No fiduciary duty</h2>
          <p>
            Your use of the Service does not create any fiduciary, advisory,
            or trust relationship between you and ClearPath. ClearPath does
            not owe you a duty of care with respect to your financial
            decisions. Always consult a licensed financial advisor, tax
            professional, and/or attorney before taking action.
          </p>

          <h2>5. Your account</h2>
          <p>
            You are responsible for maintaining the confidentiality of your
            account credentials and for all activity that occurs under your
            account. You agree to notify us promptly if you suspect
            unauthorized access. We may suspend or terminate accounts that
            violate these Terms, behave abusively, or exceed reasonable usage
            thresholds.
          </p>

          <h2>6. Brokerage connections (SnapTrade / read-only)</h2>
          <p>
            If you link a brokerage account, you authorize us and our
            integration provider (currently SnapTrade) to access{" "}
            <strong>read-only</strong> data about your holdings, account
            balances, and transactions. ClearPath does not and will not
            initiate trades, move money, or modify your brokerage account. You
            may revoke access at any time by disconnecting the account in the
            Portfolio settings.
          </p>
          <p>
            We encrypt brokerage credentials (user secrets / access tokens) at
            rest using AES-256-GCM. However, no system is perfectly secure.
            You acknowledge the residual risk of connecting external accounts
            to third-party services.
          </p>

          <h2>7. Subscription and billing</h2>
          <p>
            Some features are available only on paid plans. Pricing, features,
            and usage limits are described on our{" "}
            <Link href="/pricing" className="underline">
              Pricing
            </Link>{" "}
            page. Fees are billed in advance on a recurring basis. You may
            cancel at any time; cancellation takes effect at the end of the
            current billing period. Except where required by law, fees already
            paid are non-refundable.
          </p>
          <p>
            Usage-based limits (query caps, token allowances, cost caps) may
            change as our infrastructure costs evolve. We will provide
            reasonable notice of material changes to any paid plan.
          </p>

          <h2>8. Acceptable use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>
              Scrape, mirror, or re-distribute the Service or its outputs
              without written permission
            </li>
            <li>
              Circumvent rate limits, pay walls, authentication, or usage caps
            </li>
            <li>
              Use the Service to provide investment advice to third parties as
              if you were a licensed advisor
            </li>
            <li>
              Input information on behalf of another person without their
              consent
            </li>
            <li>
              Attempt to reverse-engineer, extract, or otherwise discover
              proprietary prompts, weights, or model fine-tuning data
            </li>
            <li>Upload or transmit malware, spam, or content that violates law</li>
            <li>
              Use the Service in a way that risks damage to any person,
              ClearPath, or our providers
            </li>
          </ul>

          <h2>9. AI output</h2>
          <p>
            The Service uses third-party AI models (including Anthropic Claude,
            OpenAI GPT, and Google Gemini) to generate analyses. Those models
            can produce content that is inaccurate or misleading. You agree
            that:
          </p>
          <ul>
            <li>You will not treat AI output as professional advice.</li>
            <li>
              You will independently verify any numeric, legal, regulatory, or
              tax claim before acting on it.
            </li>
            <li>
              You will not rely on the Service as a substitute for licensed
              professional judgment.
            </li>
          </ul>

          <h2>10. Intellectual property</h2>
          <p>
            The Service, including software, prompts, designs, brand elements,
            and aggregated analyses, is owned by ClearPath or our licensors and
            protected by intellectual-property laws. We grant you a limited,
            revocable, non-exclusive, non-transferable license to use the
            Service for your personal, non-commercial research purposes.
          </p>
          <p>
            You retain ownership of any content you submit (for example, custom
            notes or portfolios). You grant us a limited license to process
            that content solely to operate the Service.
          </p>

          <h2>11. Third-party data</h2>
          <p>
            The Service relies on data from third parties including SEC EDGAR,
            FRED (Federal Reserve Economic Data), Yahoo Finance, SnapTrade,
            and others. Those providers are solely responsible for their data;
            ClearPath makes no warranty regarding accuracy, completeness, or
            timeliness. Use of third-party data through the Service is subject
            to those providers&apos; own terms and may be revoked at any time.
          </p>

          <h2>12. Disclaimers (ALL CAPS, please read)</h2>
          <p>
            THE SERVICE IS PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS
            AVAILABLE&rdquo; BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER
            EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF
            MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT,
            OR ACCURACY. CLEARPATH DOES NOT WARRANT THAT THE SERVICE WILL BE
            UNINTERRUPTED, SECURE, OR FREE FROM ERRORS OR THAT ANY OUTPUTS WILL
            BE ACCURATE OR RELIABLE. TO THE FULLEST EXTENT PERMITTED BY LAW,
            WE DISCLAIM ALL LIABILITY FOR INVESTMENT DECISIONS YOU MAKE BASED
            ON INFORMATION FROM THE SERVICE.
          </p>

          <h2>13. Limitation of liability</h2>
          <p>
            TO THE FULLEST EXTENT PERMITTED BY LAW, CLEARPATH, ITS OFFICERS,
            EMPLOYEES, AGENTS, AND LICENSORS WILL NOT BE LIABLE FOR ANY
            INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES,
            INCLUDING LOST PROFITS, LOST DATA, OR INVESTMENT LOSSES, ARISING
            OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE — EVEN IF WE
            HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
          </p>
          <p>
            OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR
            RELATING TO THESE TERMS OR THE SERVICE WILL NOT EXCEED THE GREATER
            OF (A) ONE HUNDRED U.S. DOLLARS (US$100) OR (B) THE TOTAL FEES YOU
            PAID TO CLEARPATH IN THE TWELVE (12) MONTHS PRECEDING THE EVENT
            GIVING RISE TO THE CLAIM.
          </p>

          <h2>14. Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless ClearPath from and against
            any claims, losses, damages, liabilities, and expenses (including
            reasonable attorneys&apos; fees) arising out of (i) your use of the
            Service, (ii) your violation of these Terms, or (iii) your
            violation of any law or third-party right.
          </p>

          <h2>15. Arbitration and class-action waiver</h2>
          <p>
            To the maximum extent permitted by law, you and ClearPath agree to
            resolve any dispute arising out of or related to these Terms or the
            Service through <strong>binding individual arbitration</strong>,
            administered by the American Arbitration Association (AAA) under
            its Consumer Arbitration Rules. Arbitration takes place in the
            U.S. state where you reside or another mutually agreed location,
            and judgment on the award may be entered in any court of competent
            jurisdiction.
          </p>
          <p>
            <strong>
              You and ClearPath waive any right to bring or participate in a
              class action, class-wide arbitration, or representative
              proceeding.
            </strong>{" "}
            The arbitrator may not consolidate more than one person&apos;s
            claims or preside over any form of representative proceeding.
          </p>
          <p>
            You may opt out of arbitration within thirty (30) days of first
            accepting these Terms by emailing{" "}
            <a href="mailto:legal@clearpath-invest.com" className="underline">
              legal@clearpath-invest.com
            </a>{" "}
            with the subject line &ldquo;Arbitration Opt-Out.&rdquo;
          </p>

          <h2>16. Termination</h2>
          <p>
            You may close your account at any time. We may suspend or terminate
            your account or access to the Service at any time and for any
            reason, including for violation of these Terms. Sections that by
            their nature should survive termination (disclaimers, limits of
            liability, arbitration, indemnification) will survive.
          </p>

          <h2>17. Changes</h2>
          <p>
            We may update these Terms from time to time. If we make material
            changes, we will notify you by email or via the Service. Continued
            use of the Service after the effective date of any updated Terms
            constitutes acceptance.
          </p>

          <h2>18. Governing law</h2>
          <p>
            These Terms are governed by the laws of the State of Delaware,
            without regard to its conflict-of-law rules. Where arbitration
            does not apply, any action must be brought in the state or federal
            courts located in Delaware.
          </p>

          <h2>19. Contact</h2>
          <p>
            Questions about these Terms?{" "}
            <a href="mailto:legal@clearpath-invest.com" className="underline">
              legal@clearpath-invest.com
            </a>
            .
          </p>
        </div>
      </main>
      <MarketingFooter />
    </>
  );
}
